export const api_key = 'api_key=6171165465a508a6fa13009051243ab7'
export const api_movies = 'https://api.themoviedb.org/3/movie/'
export const api_search = 'https://api.themoviedb.org/3/search/movie'
export const api_img_small = 'https://image.tmdb.org/t/p/w300/'
export const api_img = 'https://image.tmdb.org/t/p/w500/'
export const api_img_large = 'https://image.tmdb.org/t/p/w1280/'
export const lang = 'language=pt-BR'